### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by baba990aini** [afkarxyz/spotify-down#1]
Nice to meet you. Your work has been a great help to me, and I hope this project can continue

**Comment by afkarxyz** [comment]
As long as they don't use cloudflare as a shield. Surely this project can continue.

**Comment by afkarxyz** [comment]
Since there's a new version, this repository will be deleted or made private. [Please check here for the replacement.](https://github.com/afkarxyz/SpotifyDown-GUI)
